### ISSUE TITLE
Allow for "bindToController"

### ISSUE THREAD

**Issue by jeroenverfallie** [christianalfoni/cerebral-angular#4]
Right now, injectState requires the `$scope` for the  `$destroy` event (which makes sense).
However, when using the `bindToController` option, you can't attach properties to your controller directly.

An approach like this would allow this option:
```
constructor(cerebral, $scope) {
    cerebral.injectState($scope, {
        name: ['name']
    }, 'vm');

    // sets $scope.vm.name = state.name

    // In controller, name can be accessed through this.name
    // In view, name can be accessed through {{vm.name}}
}
``` 

In other words, have an optional argument to which cerebral attaches the data, instead of the $scope.

**Comment by christianalfoni** [comment]
Hi @jeroenverfallie!

Yeah, it would be great to support this. I just wonder how we would detect that the controller is actually instantiated. With the $scope, as you say, you know when it is destroyed. But with `bindToController` there is no way to know that? We have to know it so we do run unnecessary updates.

**Comment by jeroenverfallie** [comment]
I have done some edits to my code fragment, you'd still need $scope, but also the name of the `controllerAs`, as it also lives inside of $scope. ($scope.vm for example) which you can then set the values on, instead of the $scope itself?

**Comment by christianalfoni** [comment]
Ah, okay, so "vm" in this case is the "controllerAs" value? Would it be okay to update the example with a fully featured directive with all the options, including controllerAs? Just to make sure I understand this correctly :-)
