### ISSUE TITLE
Difference between cerebral-angular and cerebral-angular-immutable-store

### ISSUE THREAD

**Issue by henriklundgren** [christianalfoni/cerebral-angular#8]
Any explanation on what the difference is between the two? When should you use a instead of b.

**Comment by Guria** [comment]
`cerebral-angular-immutable-store` is deprecated view-model combined package for old cerebralversion. Shouldn't be used.

**Comment by henriklundgren** [comment]
invested time yesterday in `cerebral-angular-immutable-store` after watching [this video](https://www.youtube.com/watch?v=YVmgLReFjLw). Got confused this morning when I noticed on the Cerebral page it was declaring `cerebral-angular`.

**Comment by christianalfoni** [comment]
@henriklundgren Yeah, sorry about this, but Cerebral has evolved very rapidly, so old videos will be confusing :-/
